services:
  app.admin.event:
    class: App\Admin\PartnerAdmin
    arguments: [~, App\Entity\Partner, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Контент, label: Список партнеров }

  app.admin.artist:
    class: App\Admin\ArtistAdmin
    arguments: [~, App\Entity\Artist, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Контент, label: Список артистов }

  app.admin.page:
    class: App\Admin\PageAdmin
    arguments: [~, App\Entity\Page, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Контент, label: Статичные страницы }

  app.admin.news:
    class: App\Admin\NewsAdmin
    arguments: [~, App\Entity\News, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Контент, label: Новости }

  app.admin.menu:
    class: App\Admin\MenuAdmin
    arguments: [~, App\Entity\Menu, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Контент, label: Меню сайта }