services:
  app.admin.event:
    class: App\Admin\PartnerAdmin
    arguments: [~, App\Entity\Partner, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Контент, label: Список партнеров }

  app.admin.artist:
    class: App\Admin\ArtistAdmin
    arguments: [~, App\Entity\Artist, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Контент, label: Список артистов }

  app.admin.page:
    class: App\Admin\PageAdmin
    arguments: [~, App\Entity\Page, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Контент, label: Статичные страницы }

  app.admin.news:
    class: App\Admin\NewsAdmin
    arguments: [~, App\Entity\News, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Контент, label: Новости }

  app.admin.slider:
    class: App\Admin\SliderAdmin
    arguments: [~, App\Entity\Slider, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Контент, label: Слайды }

  app.admin.menu:
    class: App\Admin\MenuAdmin
    arguments: [~, App\Entity\Menu, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Контент, label: Меню сайта }

  app.admin.history:
    class: App\Admin\HistoryAdmin
    arguments: [~, App\Entity\History, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Контент, label: История, show_in_dashboard: false }

  app.admin.zone:
    class: App\Admin\ZoneAdmin
    arguments: [~, App\Entity\Zone, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Контент, label: Фан-зоны }

  app.admin.zone_lineup:
    class: App\Admin\ZoneLineupAdmin
    arguments: [~, App\Entity\ZoneLineup, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Контент, label: Расписание, show_in_dashboard: false }