fos_ck_editor:
    input_sync: true
    default_config: default
    configs:
        default:
            filebrowserUploadMethod: form
            filebrowserBrowseRoute: admin_sonata_media_media_browser
            filebrowserImageBrowseRoute: admin_sonata_media_media_browser
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
            filebrowserUploadRoute: admin_sonata_media_media_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
            filebrowserImageUploadRoute: admin_sonata_media_media_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
            extraPlugins: "templates"
            templates:    "my_templates"
        templates:
            my_templates:
                imagesPath: "/bundles/mybundle/templates/images"
                templates:
                    - title:       "My Template"
                      image:       "image.jpg"
                      description: "My awesome template"
                      html:        "<p>Crazy template :)</p>"