language: php
sudo: true

dist: xenial

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit

env:
  global:
    - SYMFONY_PHPUNIT_DIR=./bin/.phpunit
    - SYMFONY_DEPRECATIONS_HELPER=weak

matrix:
  fast_finish: true
  include:
    - php: 7.3

before_install:
  - cp .env.travis .env
  - cp .env.travis .env.test
  - composer self-update
  - pear config-set preferred_state beta
  - pecl channel-update pecl.php.net
  - yes | pecl install imagick
  - yarn install
  - yarn build

install:
  - ./bin/setup-test.sh

script:
  - ./bin/console lint:yaml config
  - ./bin/console lint:twig templates
  - ./bin/console lint:xliff translations
  - ./bin/console security:check
  - ./bin/console doctrine:schema:validate -vvv --no-interaction
  - ./vendor/bin/simple-phpunit
