monolog:
    channels: ['feedback', 'mailchimp']
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]

        feedback:
            type:  rotating_file
            level: debug
            path:  "%kernel.logs_dir%/feedback/feedback-%kernel.environment%.log"
            channels: ["feedback"]

        mailchimp:
            type:  rotating_file
            level: debug
            path:  "%kernel.logs_dir%/mailchimp/mailchimp-%kernel.environment%.log"
            channels: ["mailchimp"]
