adw_seo:
    resource: "@ADWSEOBundle/Admin/Controller/"
    type:     annotation

admin_sonata_media_media_browser:
    path: /admin/sonata/media/media/browser
    controller: CoopTilleuls\Bundle\CKEditorSonataMediaBundle\Controller\MediaAdminController::browserAction
    defaults:
        _sonata_admin: sonata.media.admin.media

admin_sonata_media_media_upload:
    path: /admin/sonata/media/media/upload
    controller: CoopTilleuls\Bundle\CKEditorSonataMediaBundle\Controller\MediaAdminController::uploadAction
    defaults:
        _sonata_admin: sonata.media.admin.media

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting

controllers:
    resource: ../src/Controller/
    type: annotation

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
